@GraphQLAPI_HostAddress = http://localhost:5126

## Rest API ##
### Get Supplier By id ###
GET {{GraphQLAPI_HostAddress}}/api/supplier

### Get all Supplier ###
GET {{GraphQLAPI_HostAddress}}/api/supplier/2

## GraphQL API ##

### Get all Supplier ###
POST {{GraphQLAPI_HostAddress}}/graphQL
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
    allSuppliers{
        id
        firstName
        lastName
    }
}

### Get Supplier By id ###
POST {{GraphQLAPI_HostAddress}}/graphQL
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  supplierById(id:2){
    firstName
    address
    phone
  }
}

### Create Supplier ###
POST {{GraphQLAPI_HostAddress}}/graphQL
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  addSupplier(newSupplier: {
    firstName: "Faii"
    lastName: "Kook"
    address: "1234 Main St"
    phone: "123-456-7890"
    email: "faii@adc.com"
  }) {
    id
    firstName
    lastName
    address
    phone
    email
  }
}

### Update Supplier ###
POST {{GraphQLAPI_HostAddress}}/graphQL
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateSupplier(
   id: 30002,
   supplier: {
    id: 30002
    firstName: "Faii"
    lastName: "Faii"
    address: "1234 Main St"
    phone: "123-456-7890"
    email: "faii@adc.com"
  }) {
    id
    firstName
    lastName
    address
    phone
    email
  }
}

### Update Supplier Id Not Exist ###
POST {{GraphQLAPI_HostAddress}}/graphQL
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateSupplier(
   id: 99999,
   supplier: {
    id: 99999
    firstName: "Faii"
    lastName: "Faii"
    address: "1234 Main St"
    phone: "123-456-7890"
    email: "faii@adc.com"
  }) {
    id
    firstName
    lastName
    address
    phone
    email
  }
}

### Delete Supplier ###
POST {{GraphQLAPI_HostAddress}}/graphQL
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  deleteSupplier(id: 30002)
}